### ISSUE TITLE
Display beacons on map

### ISSUE THREAD

**Issue by yzueger** [G12-Wanderwave/Wanderwave#34]

**Comment by joriba** [comment]
@Imade I have already done some templating for this issue (although It does not really work yet, I haven't been able to fully figure out the Room database). I'll publish it on a new "show-beacons-on-map" branch if you want to use it...

**Comment by IB-12** [comment]
@joriba Alright I'll check it out thanks. I'll try to keep it as flexible as possible to maintain compatibility.
