### ISSUE TITLE
Define some beacons in database/clous

### ISSUE THREAD

**Issue by yzueger** [G12-Wanderwave/Wanderwave#35]

**Comment by IB-12** [comment]
I have an SQLite Error in BeaconDAO when I try to run the code. It can't find a table named "beacons" despite one already existing in Firebase. I'm still trying to figure it out and any inputs would be appreciated :)

**Comment by joriba** [comment]
So this is with the template code I wrote for the Map issue, I assume? I had the same error there, but postponed fixing it when I saw you assigned yourself to the issue.
Right now, it does not do anything with the Firebase database, just the local "demo_data.db" file in assets. You should be able to edit it using SQLite, and add the "beacons" table with the correct attributes (see the beacon dao).
Hope that helps!

**Comment by IB-12** [comment]
Ah I see, thank you !
